var hierarchy =
[
    [ "Accelerometer", "class_accelerometer.html", [
      [ "ADXL345_I2C", "class_a_d_x_l345___i2_c.html", null ],
      [ "ADXL345_SPI", "class_a_d_x_l345___s_p_i.html", null ],
      [ "ADXL362", "class_a_d_x_l362.html", null ],
      [ "BuiltInAccelerometer", "class_built_in_accelerometer.html", null ]
    ] ],
    [ "AIMGradeReport_struct", "struct_a_i_m_grade_report__struct.html", null ],
    [ "ADXL345_SPI::AllAxes", "struct_a_d_x_l345___s_p_i_1_1_all_axes.html", null ],
    [ "ADXL345_I2C::AllAxes", "struct_a_d_x_l345___i2_c_1_1_all_axes.html", null ],
    [ "ADXL362::AllAxes", "struct_a_d_x_l362_1_1_all_axes.html", null ],
    [ "Annulus_struct", "struct_annulus__struct.html", null ],
    [ "ArcInfo2_struct", "struct_arc_info2__struct.html", null ],
    [ "ArcInfo_struct", "struct_arc_info__struct.html", null ],
    [ "AVIInfo_struct", "struct_a_v_i_info__struct.html", null ],
    [ "AxisReport_struct", "struct_axis_report__struct.html", null ],
    [ "Barcode2DInfo_struct", "struct_barcode2_d_info__struct.html", null ],
    [ "BarcodeInfo_struct", "struct_barcode_info__struct.html", null ],
    [ "BCGOptions_struct", "struct_b_c_g_options__struct.html", null ],
    [ "BestCircle2_struct", "struct_best_circle2__struct.html", null ],
    [ "BestCircle_struct", "struct_best_circle__struct.html", null ],
    [ "BestEllipse2_struct", "struct_best_ellipse2__struct.html", null ],
    [ "BestEllipse_struct", "struct_best_ellipse__struct.html", null ],
    [ "BestLine_struct", "struct_best_line__struct.html", null ],
    [ "BrowserOptions_struct", "struct_browser_options__struct.html", null ],
    [ "ButtonScheduler", "class_button_scheduler.html", [
      [ "CancelButtonScheduler", "class_cancel_button_scheduler.html", null ],
      [ "HeldButtonScheduler", "class_held_button_scheduler.html", null ],
      [ "PressedButtonScheduler", "class_pressed_button_scheduler.html", null ],
      [ "ReleasedButtonScheduler", "class_released_button_scheduler.html", null ],
      [ "ToggleButtonScheduler", "class_toggle_button_scheduler.html", null ]
    ] ],
    [ "CalibrationAxisInfo_struct", "struct_calibration_axis_info__struct.html", null ],
    [ "CalibrationInfo_struct", "struct_calibration_info__struct.html", null ],
    [ "CalibrationLearnSetupInfo_struct", "struct_calibration_learn_setup_info__struct.html", null ],
    [ "CalibrationPoints_struct", "struct_calibration_points__struct.html", null ],
    [ "CalibrationReferencePoints_struct", "struct_calibration_reference_points__struct.html", null ],
    [ "CaliperOptions_struct", "struct_caliper_options__struct.html", null ],
    [ "CaliperReport_struct", "struct_caliper_report__struct.html", null ],
    [ "CANInterfacePlugin", "class_c_a_n_interface_plugin.html", null ],
    [ "CannyOptions_struct", "struct_canny_options__struct.html", null ],
    [ "CharacterStatistics_struct", "struct_character_statistics__struct.html", null ],
    [ "CharInfo2_struct", "struct_char_info2__struct.html", null ],
    [ "CharInfo_struct", "struct_char_info__struct.html", null ],
    [ "CharReport2_struct", "struct_char_report2__struct.html", null ],
    [ "CharReport3_struct", "struct_char_report3__struct.html", null ],
    [ "CharReport_struct", "struct_char_report__struct.html", null ],
    [ "CIELabValue_struct", "struct_c_i_e_lab_value__struct.html", null ],
    [ "CIEXYZValue_struct", "struct_c_i_e_x_y_z_value__struct.html", null ],
    [ "CircleDescriptor_struct", "struct_circle_descriptor__struct.html", null ],
    [ "CircleFeature_struct", "struct_circle_feature__struct.html", null ],
    [ "CircleFitOptions_struct", "struct_circle_fit_options__struct.html", null ],
    [ "CircleMatch_struct", "struct_circle_match__struct.html", null ],
    [ "CircleReport_struct", "struct_circle_report__struct.html", null ],
    [ "CircularBuffer< T >", "class_circular_buffer.html", null ],
    [ "CircularBuffer< double >", "class_circular_buffer.html", null ],
    [ "ClampMax2Report_struct", "struct_clamp_max2_report__struct.html", null ],
    [ "ClampOverlaySettings_struct", "struct_clamp_overlay_settings__struct.html", null ],
    [ "ClampPoints_struct", "struct_clamp_points__struct.html", null ],
    [ "ClampResults_struct", "struct_clamp_results__struct.html", null ],
    [ "ClampSettings_struct", "struct_clamp_settings__struct.html", null ],
    [ "ClassifiedCurve_struct", "struct_classified_curve__struct.html", null ],
    [ "ClassifiedDisparity_struct", "struct_classified_disparity__struct.html", null ],
    [ "ClassifierAccuracyReport_struct", "struct_classifier_accuracy_report__struct.html", null ],
    [ "ClassifierReport_struct", "struct_classifier_report__struct.html", null ],
    [ "ClassifierReportAdvanced_struct", "struct_classifier_report_advanced__struct.html", null ],
    [ "ClassifierSampleInfo_struct", "struct_classifier_sample_info__struct.html", null ],
    [ "ClassifyDistancesReport_struct", "struct_classify_distances_report__struct.html", null ],
    [ "ClassScore_struct", "struct_class_score__struct.html", null ],
    [ "ClosedContour_struct", "struct_closed_contour__struct.html", null ],
    [ "ClosedCurveFeature_struct", "struct_closed_curve_feature__struct.html", null ],
    [ "Color2_union", "union_color2__union.html", null ],
    [ "Color_union", "union_color__union.html", null ],
    [ "ColorHistogramReport_struct", "struct_color_histogram_report__struct.html", null ],
    [ "ColorInformation_struct", "struct_color_information__struct.html", null ],
    [ "ColorOptions_struct", "struct_color_options__struct.html", null ],
    [ "ColorReport_struct", "struct_color_report__struct.html", null ],
    [ "ColorSegmenationOptions_struct", "struct_color_segmenation_options__struct.html", null ],
    [ "CommandGroupEntry", "class_command_group_entry.html", null ],
    [ "Complex_struct", "struct_complex__struct.html", null ],
    [ "ComputeDistancesReport_struct", "struct_compute_distances_report__struct.html", null ],
    [ "ConcentricEdgeFitOptions_struct", "struct_concentric_edge_fit_options__struct.html", null ],
    [ "ConcentricRakeReport2_struct", "struct_concentric_rake_report2__struct.html", null ],
    [ "ConcentricRakeReport_struct", "struct_concentric_rake_report__struct.html", null ],
    [ "ConnectionConstraint_struct", "struct_connection_constraint__struct.html", null ],
    [ "ConstCurveFeature_struct", "struct_const_curve_feature__struct.html", null ],
    [ "ConstructROIOptions2_struct", "struct_construct_r_o_i_options2__struct.html", null ],
    [ "ConstructROIOptions_struct", "struct_construct_r_o_i_options__struct.html", null ],
    [ "ContourComputeCurvatureReport_struct", "struct_contour_compute_curvature_report__struct.html", null ],
    [ "ContourFitLineReport_struct", "struct_contour_fit_line_report__struct.html", null ],
    [ "ContourFitPolynomialReport_struct", "struct_contour_fit_polynomial_report__struct.html", null ],
    [ "ContourFitSplineReport_struct", "struct_contour_fit_spline_report__struct.html", null ],
    [ "ContourInfo2_struct", "struct_contour_info2__struct.html", null ],
    [ "ContourInfo_struct", "struct_contour_info__struct.html", null ],
    [ "ContourInfoReport_struct", "struct_contour_info_report__struct.html", null ],
    [ "ContourOverlaySettings_struct", "struct_contour_overlay_settings__struct.html", null ],
    [ "ContourPoint_struct", "struct_contour_point__struct.html", null ],
    [ "ContourUnion_union", "union_contour_union__union.html", null ],
    [ "Controller", "class_controller.html", [
      [ "PIDInterface", "class_p_i_d_interface.html", [
        [ "CANTalon", "class_c_a_n_talon.html", null ],
        [ "PIDController", "class_p_i_d_controller.html", null ]
      ] ]
    ] ],
    [ "ControllerPower", "class_controller_power.html", null ],
    [ "ControlWord_t", "struct_control_word__t.html", null ],
    [ "CooccurrenceOptions_struct", "struct_cooccurrence_options__struct.html", null ],
    [ "CoordinateSystem_struct", "struct_coordinate_system__struct.html", null ],
    [ "CoordinateTransform2_struct", "struct_coordinate_transform2__struct.html", null ],
    [ "CoordinateTransform_struct", "struct_coordinate_transform__struct.html", null ],
    [ "CornerFeature_struct", "struct_corner_feature__struct.html", null ],
    [ "CounterBase", "class_counter_base.html", [
      [ "Counter", "class_counter.html", [
        [ "GearTooth", "class_gear_tooth.html", null ]
      ] ],
      [ "Encoder", "class_encoder.html", null ]
    ] ],
    [ "CurvatureAnalysisReport_struct", "struct_curvature_analysis_report__struct.html", null ],
    [ "Curve_struct", "struct_curve__struct.html", null ],
    [ "CurveOptions_struct", "struct_curve_options__struct.html", null ],
    [ "CurveParameters_struct", "struct_curve_parameters__struct.html", null ],
    [ "DataMatrixDescriptionOptions_struct", "struct_data_matrix_description_options__struct.html", null ],
    [ "DataMatrixOptions_struct", "struct_data_matrix_options__struct.html", null ],
    [ "DataMatrixReport_struct", "struct_data_matrix_report__struct.html", null ],
    [ "DataMatrixSearchOptions_struct", "struct_data_matrix_search_options__struct.html", null ],
    [ "DataMatrixSizeOptions_struct", "struct_data_matrix_size_options__struct.html", null ],
    [ "DetectExtremesOptions_struct", "struct_detect_extremes_options__struct.html", null ],
    [ "Disparity_struct", "struct_disparity__struct.html", null ],
    [ "DisplacementVector_struct", "struct_displacement_vector__struct.html", null ],
    [ "DisplayMapping_struct", "struct_display_mapping__struct.html", null ],
    [ "DistortionModelParams_struct", "struct_distortion_model_params__struct.html", null ],
    [ "DivisionModel_struct", "struct_division_model__struct.html", null ],
    [ "DrawTextOptions_struct", "struct_draw_text_options__struct.html", null ],
    [ "EdgeInfo_struct", "struct_edge_info__struct.html", null ],
    [ "EdgeLocationReport_struct", "struct_edge_location_report__struct.html", null ],
    [ "EdgeOptions2_struct", "struct_edge_options2__struct.html", null ],
    [ "EdgeOptions_struct", "struct_edge_options__struct.html", null ],
    [ "EdgePolarity_struct", "struct_edge_polarity__struct.html", null ],
    [ "EdgeReport2_struct", "struct_edge_report2__struct.html", null ],
    [ "EdgeReport_struct", "struct_edge_report__struct.html", null ],
    [ "EllipseDescriptor_struct", "struct_ellipse_descriptor__struct.html", null ],
    [ "EllipseFeature_struct", "struct_ellipse_feature__struct.html", null ],
    [ "EllipseMatch_struct", "struct_ellipse_match__struct.html", null ],
    [ "Error", "class_error.html", null ],
    [ "ErrorBase", "class_error_base.html", [
      [ "AxisCamera", "class_axis_camera.html", null ],
      [ "CameraServer", "class_camera_server.html", null ],
      [ "CANJaguar", "class_c_a_n_jaguar.html", null ],
      [ "CANTalon", "class_c_a_n_talon.html", null ],
      [ "Command", "class_command.html", [
        [ "CommandGroup", "class_command_group.html", null ],
        [ "PIDCommand", "class_p_i_d_command.html", null ],
        [ "PrintCommand", "class_print_command.html", null ],
        [ "StartCommand", "class_start_command.html", null ],
        [ "WaitCommand", "class_wait_command.html", null ],
        [ "WaitForChildren", "class_wait_for_children.html", null ],
        [ "WaitUntilCommand", "class_wait_until_command.html", null ]
      ] ],
      [ "ImageBase", "class_image_base.html", [
        [ "ColorImage", "class_color_image.html", [
          [ "HSLImage", "class_h_s_l_image.html", null ],
          [ "RGBImage", "class_r_g_b_image.html", null ]
        ] ],
        [ "MonoImage", "class_mono_image.html", [
          [ "BinaryImage", "class_binary_image.html", null ]
        ] ]
      ] ],
      [ "Joystick", "class_joystick.html", null ],
      [ "MotorSafetyHelper", "class_motor_safety_helper.html", null ],
      [ "Notifier", "class_notifier.html", null ],
      [ "Preferences", "class_preferences.html", null ],
      [ "Resource", "class_resource.html", null ],
      [ "RobotDrive", "class_robot_drive.html", null ],
      [ "Scheduler", "class_scheduler.html", null ],
      [ "SensorBase", "class_sensor_base.html", [
        [ "AnalogAccelerometer", "class_analog_accelerometer.html", null ],
        [ "AnalogInput", "class_analog_input.html", null ],
        [ "AnalogOutput", "class_analog_output.html", null ],
        [ "AnalogTrigger", "class_analog_trigger.html", null ],
        [ "BuiltInAccelerometer", "class_built_in_accelerometer.html", null ],
        [ "Compressor", "class_compressor.html", null ],
        [ "Counter", "class_counter.html", null ],
        [ "DigitalGlitchFilter", "class_digital_glitch_filter.html", null ],
        [ "DriverStation", "class_driver_station.html", null ],
        [ "Encoder", "class_encoder.html", null ],
        [ "GyroBase", "class_gyro_base.html", [
          [ "ADXRS450_Gyro", "class_a_d_x_r_s450___gyro.html", null ],
          [ "AnalogGyro", "class_analog_gyro.html", null ]
        ] ],
        [ "I2C", "class_i2_c.html", [
          [ "ADXL345_I2C", "class_a_d_x_l345___i2_c.html", null ]
        ] ],
        [ "InterruptableSensorBase", "class_interruptable_sensor_base.html", [
          [ "DigitalSource", "class_digital_source.html", [
            [ "AnalogTriggerOutput", "class_analog_trigger_output.html", null ],
            [ "DigitalInput", "class_digital_input.html", null ],
            [ "DigitalOutput", "class_digital_output.html", null ]
          ] ]
        ] ],
        [ "PowerDistributionPanel", "class_power_distribution_panel.html", null ],
        [ "PWM", "class_p_w_m.html", [
          [ "SafePWM", "class_safe_p_w_m.html", [
            [ "Jaguar", "class_jaguar.html", null ],
            [ "SD540", "class_s_d540.html", null ],
            [ "Servo", "class_servo.html", null ],
            [ "Spark", "class_spark.html", null ],
            [ "Talon", "class_talon.html", null ],
            [ "TalonSRX", "class_talon_s_r_x.html", null ],
            [ "Victor", "class_victor.html", null ],
            [ "VictorSP", "class_victor_s_p.html", null ]
          ] ]
        ] ],
        [ "Relay", "class_relay.html", null ],
        [ "SmartDashboard", "class_smart_dashboard.html", null ],
        [ "SolenoidBase", "class_solenoid_base.html", [
          [ "DoubleSolenoid", "class_double_solenoid.html", null ],
          [ "Solenoid", "class_solenoid.html", null ]
        ] ],
        [ "SPI", "class_s_p_i.html", [
          [ "ADXL345_SPI", "class_a_d_x_l345___s_p_i.html", null ]
        ] ],
        [ "Ultrasonic", "class_ultrasonic.html", null ]
      ] ],
      [ "SerialPort", "class_serial_port.html", null ],
      [ "Subsystem", "class_subsystem.html", [
        [ "PIDSubsystem", "class_p_i_d_subsystem.html", null ]
      ] ],
      [ "Task", "class_task.html", null ],
      [ "USBCamera", "class_u_s_b_camera.html", null ]
    ] ],
    [ "ErrorStatistics_struct", "struct_error_statistics__struct.html", null ],
    [ "ExtractContourReport_struct", "struct_extract_contour_report__struct.html", null ],
    [ "ExtractTextureFeaturesReport_struct", "struct_extract_texture_features_report__struct.html", null ],
    [ "ExtremeReport_struct", "struct_extreme_report__struct.html", null ],
    [ "FeatureData_struct", "struct_feature_data__struct.html", null ],
    [ "FindCircularEdgeOptions_struct", "struct_find_circular_edge_options__struct.html", null ],
    [ "FindCircularEdgeReport_struct", "struct_find_circular_edge_report__struct.html", null ],
    [ "FindConcentricEdgeOptions_struct", "struct_find_concentric_edge_options__struct.html", null ],
    [ "FindConcentricEdgeReport_struct", "struct_find_concentric_edge_report__struct.html", null ],
    [ "FindEdgeOptions2_struct", "struct_find_edge_options2__struct.html", null ],
    [ "FindEdgeReport_struct", "struct_find_edge_report__struct.html", null ],
    [ "FindTransformRectOptions2_struct", "struct_find_transform_rect_options2__struct.html", null ],
    [ "FindTransformRectsOptions2_struct", "struct_find_transform_rects_options2__struct.html", null ],
    [ "FitCircleOptions_struct", "struct_fit_circle_options__struct.html", null ],
    [ "FitEllipseOptions_struct", "struct_fit_ellipse_options__struct.html", null ],
    [ "FitLineOptions_struct", "struct_fit_line_options__struct.html", null ],
    [ "FocalLength_struct", "struct_focal_length__struct.html", null ],
    [ "GenericHID", "class_generic_h_i_d.html", [
      [ "Joystick", "class_joystick.html", null ]
    ] ],
    [ "GeometricAdvancedSetupDataOption_struct", "struct_geometric_advanced_setup_data_option__struct.html", null ],
    [ "GeometricFeature_union", "union_geometric_feature__union.html", null ],
    [ "GeometricPatternMatch2_struct", "struct_geometric_pattern_match2__struct.html", null ],
    [ "GeometricPatternMatch3_struct", "struct_geometric_pattern_match3__struct.html", null ],
    [ "GeometricPatternMatch_struct", "struct_geometric_pattern_match__struct.html", null ],
    [ "GetCalibrationInfoReport_struct", "struct_get_calibration_info_report__struct.html", null ],
    [ "GetCameraParametersReport_struct", "struct_get_camera_parameters_report__struct.html", null ],
    [ "GridDescriptor_struct", "struct_grid_descriptor__struct.html", null ],
    [ "Gyro", "class_gyro.html", [
      [ "GyroBase", "class_gyro_base.html", null ]
    ] ],
    [ "HasBeenMoved", "struct_has_been_moved.html", null ],
    [ "HistogramReport_struct", "struct_histogram_report__struct.html", null ],
    [ "HLUsageReporting", "class_h_l_usage_reporting.html", null ],
    [ "HLUsageReportingInterface", "class_h_l_usage_reporting_interface.html", [
      [ "HardwareHLReporting", "class_hardware_h_l_reporting.html", null ]
    ] ],
    [ "HSIValue_struct", "struct_h_s_i_value__struct.html", null ],
    [ "HSLValue_struct", "struct_h_s_l_value__struct.html", null ],
    [ "HSVValue_struct", "struct_h_s_v_value__struct.html", null ],
    [ "ImageInfo_struct", "struct_image_info__struct.html", null ],
    [ "ImageSize_struct", "struct_image_size__struct.html", null ],
    [ "IMAQdxAttributeInformation_struct", "struct_i_m_a_qdx_attribute_information__struct.html", null ],
    [ "IMAQdxCameraFile_struct", "struct_i_m_a_qdx_camera_file__struct.html", null ],
    [ "IMAQdxCameraInformation_struct", "struct_i_m_a_qdx_camera_information__struct.html", null ],
    [ "IMAQdxEnumItem_struct", "struct_i_m_a_qdx_enum_item__struct.html", null ],
    [ "InspectionAlignment_struct", "struct_inspection_alignment__struct.html", null ],
    [ "InspectionOptions_struct", "struct_inspection_options__struct.html", null ],
    [ "InternalParameters_struct", "struct_internal_parameters__struct.html", null ],
    [ "ITableListener", null, [
      [ "CANJaguar", "class_c_a_n_jaguar.html", null ],
      [ "CANTalon", "class_c_a_n_talon.html", null ],
      [ "Command", "class_command.html", null ],
      [ "Compressor", "class_compressor.html", null ],
      [ "DigitalOutput", "class_digital_output.html", null ],
      [ "DoubleSolenoid", "class_double_solenoid.html", null ],
      [ "LiveWindowStatusListener", "class_live_window_status_listener.html", null ],
      [ "PIDController", "class_p_i_d_controller.html", null ],
      [ "PWM", "class_p_w_m.html", null ],
      [ "Relay", "class_relay.html", null ],
      [ "Solenoid", "class_solenoid.html", null ]
    ] ],
    [ "JoystickAxes_t", "struct_joystick_axes__t.html", null ],
    [ "JoystickPOV_t", "struct_joystick_p_o_v__t.html", null ],
    [ "JPEG2000FileAdvancedOptions_struct", "struct_j_p_e_g2000_file_advanced_options__struct.html", null ],
    [ "LabelToROIReport_struct", "struct_label_to_r_o_i_report__struct.html", null ],
    [ "LCDOptions_struct", "struct_l_c_d_options__struct.html", null ],
    [ "LCDReport_struct", "struct_l_c_d_report__struct.html", null ],
    [ "LCDSegments_struct", "struct_l_c_d_segments__struct.html", null ],
    [ "LearnCalibrationOptions_struct", "struct_learn_calibration_options__struct.html", null ],
    [ "LearnColorPatternOptions_struct", "struct_learn_color_pattern_options__struct.html", null ],
    [ "LearnGeometricPatternAdvancedOptions2_struct", "struct_learn_geometric_pattern_advanced_options2__struct.html", null ],
    [ "LearnGeometricPatternAdvancedOptions_struct", "struct_learn_geometric_pattern_advanced_options__struct.html", null ],
    [ "LearnPatternAdvancedOptions_struct", "struct_learn_pattern_advanced_options__struct.html", null ],
    [ "LearnPatternAdvancedRotationOptions_struct", "struct_learn_pattern_advanced_rotation_options__struct.html", null ],
    [ "LearnPatternAdvancedShiftOptions_struct", "struct_learn_pattern_advanced_shift_options__struct.html", null ],
    [ "LegFeature_struct", "struct_leg_feature__struct.html", null ],
    [ "Line_struct", "struct_line__struct.html", null ],
    [ "LinearAverages_struct", "struct_linear_averages__struct.html", null ],
    [ "LineDescriptor_struct", "struct_line_descriptor__struct.html", null ],
    [ "LineEquation_struct", "struct_line_equation__struct.html", null ],
    [ "LineFeature_struct", "struct_line_feature__struct.html", null ],
    [ "LineFloat_struct", "struct_line_float__struct.html", null ],
    [ "LineMatch_struct", "struct_line_match__struct.html", null ],
    [ "LineProfile_struct", "struct_line_profile__struct.html", null ],
    [ "LiveWindow", "class_live_window.html", null ],
    [ "LiveWindowComponent", "struct_live_window_component.html", null ],
    [ "MatchColorPatternOptions_struct", "struct_match_color_pattern_options__struct.html", null ],
    [ "MatchGeometricPatternAdvancedOptions2_struct", "struct_match_geometric_pattern_advanced_options2__struct.html", null ],
    [ "MatchGeometricPatternAdvancedOptions3_struct", "struct_match_geometric_pattern_advanced_options3__struct.html", null ],
    [ "MatchGeometricPatternAdvancedOptions_struct", "struct_match_geometric_pattern_advanced_options__struct.html", null ],
    [ "MatchGeometricPatternOptions_struct", "struct_match_geometric_pattern_options__struct.html", null ],
    [ "MatchMode_struct", "struct_match_mode__struct.html", null ],
    [ "MatchPatternAdvancedOptions_struct", "struct_match_pattern_advanced_options__struct.html", null ],
    [ "MatchPatternOptions_struct", "struct_match_pattern_options__struct.html", null ],
    [ "MaxGridSize_struct", "struct_max_grid_size__struct.html", null ],
    [ "MeasureParticlesReport_struct", "struct_measure_particles_report__struct.html", null ],
    [ "MeterArc_struct", "struct_meter_arc__struct.html", null ],
    [ "CANTalon::MotionProfileStatus", "struct_c_a_n_talon_1_1_motion_profile_status.html", null ],
    [ "MotorSafety", "class_motor_safety.html", [
      [ "CANJaguar", "class_c_a_n_jaguar.html", null ],
      [ "CANTalon", "class_c_a_n_talon.html", null ],
      [ "Relay", "class_relay.html", null ],
      [ "RobotDrive", "class_robot_drive.html", null ],
      [ "SafePWM", "class_safe_p_w_m.html", null ]
    ] ],
    [ "NearestNeighborClassResult_struct", "struct_nearest_neighbor_class_result__struct.html", null ],
    [ "NearestNeighborOptions_struct", "struct_nearest_neighbor_options__struct.html", null ],
    [ "NearestNeighborTrainingReport_struct", "struct_nearest_neighbor_training_report__struct.html", null ],
    [ "NullDeleter< T >", "struct_null_deleter.html", null ],
    [ "OCRProcessingOptions_struct", "struct_o_c_r_processing_options__struct.html", null ],
    [ "OCRSpacingOptions_struct", "struct_o_c_r_spacing_options__struct.html", null ],
    [ "OpenContour_struct", "struct_open_contour__struct.html", null ],
    [ "OverlayTextOptions_struct", "struct_overlay_text_options__struct.html", null ],
    [ "PairOfParallelLinePairsFeature_struct", "struct_pair_of_parallel_line_pairs_feature__struct.html", null ],
    [ "ParallelLinePairFeature_struct", "struct_parallel_line_pair_feature__struct.html", null ],
    [ "PartialCircle_struct", "struct_partial_circle__struct.html", null ],
    [ "PartialEllipse_struct", "struct_partial_ellipse__struct.html", null ],
    [ "ParticleAnalysisReport_struct", "struct_particle_analysis_report__struct.html", null ],
    [ "ParticleClassifierAutoThresholdOptions_struct", "struct_particle_classifier_auto_threshold_options__struct.html", null ],
    [ "ParticleClassifierLocalThresholdOptions_struct", "struct_particle_classifier_local_threshold_options__struct.html", null ],
    [ "ParticleClassifierOptions_struct", "struct_particle_classifier_options__struct.html", null ],
    [ "ParticleClassifierPreprocessingOptions2_struct", "struct_particle_classifier_preprocessing_options2__struct.html", null ],
    [ "ParticleClassifierPreprocessingOptions_struct", "struct_particle_classifier_preprocessing_options__struct.html", null ],
    [ "ParticleFilterCriteria2_struct", "struct_particle_filter_criteria2__struct.html", null ],
    [ "ParticleFilterCriteria_struct", "struct_particle_filter_criteria__struct.html", null ],
    [ "ParticleFilterOptions2_struct", "struct_particle_filter_options2__struct.html", null ],
    [ "ParticleFilterOptions_struct", "struct_particle_filter_options__struct.html", null ],
    [ "ParticleReport_struct", "struct_particle_report__struct.html", null ],
    [ "PatternMatch_struct", "struct_pattern_match__struct.html", null ],
    [ "pcre_callout_block", "structpcre__callout__block.html", null ],
    [ "pcre_extra", "structpcre__extra.html", null ],
    [ "PIDOutput", "class_p_i_d_output.html", [
      [ "PIDCommand", "class_p_i_d_command.html", null ],
      [ "PIDSubsystem", "class_p_i_d_subsystem.html", null ],
      [ "SpeedController", "class_speed_controller.html", [
        [ "CANSpeedController", "class_c_a_n_speed_controller.html", [
          [ "CANJaguar", "class_c_a_n_jaguar.html", null ],
          [ "CANTalon", "class_c_a_n_talon.html", null ]
        ] ],
        [ "Jaguar", "class_jaguar.html", null ],
        [ "SD540", "class_s_d540.html", null ],
        [ "Spark", "class_spark.html", null ],
        [ "Talon", "class_talon.html", null ],
        [ "TalonSRX", "class_talon_s_r_x.html", null ],
        [ "Victor", "class_victor.html", null ],
        [ "VictorSP", "class_victor_s_p.html", null ]
      ] ]
    ] ],
    [ "PIDSource", "class_p_i_d_source.html", [
      [ "AnalogAccelerometer", "class_analog_accelerometer.html", null ],
      [ "AnalogInput", "class_analog_input.html", null ],
      [ "CANTalon", "class_c_a_n_talon.html", null ],
      [ "Encoder", "class_encoder.html", null ],
      [ "Filter", "class_filter.html", [
        [ "LinearDigitalFilter", "class_linear_digital_filter.html", null ]
      ] ],
      [ "GyroBase", "class_gyro_base.html", null ],
      [ "PIDCommand", "class_p_i_d_command.html", null ],
      [ "PIDSubsystem", "class_p_i_d_subsystem.html", null ],
      [ "Potentiometer", "class_potentiometer.html", [
        [ "AnalogPotentiometer", "class_analog_potentiometer.html", null ]
      ] ],
      [ "Ultrasonic", "class_ultrasonic.html", null ]
    ] ],
    [ "PixelValue_union", "union_pixel_value__union.html", null ],
    [ "Point_struct", "struct_point__struct.html", null ],
    [ "PointDouble_struct", "struct_point_double__struct.html", null ],
    [ "PointDoublePair_struct", "struct_point_double_pair__struct.html", null ],
    [ "PointFloat_struct", "struct_point_float__struct.html", null ],
    [ "PolyModel_struct", "struct_poly_model__struct.html", null ],
    [ "QRCodeDataToken_struct", "struct_q_r_code_data_token__struct.html", null ],
    [ "QRCodeDescriptionOptions_struct", "struct_q_r_code_description_options__struct.html", null ],
    [ "QRCodeReport_struct", "struct_q_r_code_report__struct.html", null ],
    [ "QRCodeSearchOptions_struct", "struct_q_r_code_search_options__struct.html", null ],
    [ "QRCodeSizeOptions_struct", "struct_q_r_code_size_options__struct.html", null ],
    [ "QuantifyData_struct", "struct_quantify_data__struct.html", null ],
    [ "QuantifyReport_struct", "struct_quantify_report__struct.html", null ],
    [ "RakeOptions_struct", "struct_rake_options__struct.html", null ],
    [ "RakeReport2_struct", "struct_rake_report2__struct.html", null ],
    [ "RakeReport_struct", "struct_rake_report__struct.html", null ],
    [ "Range_struct", "struct_range__struct.html", null ],
    [ "RangeDouble_struct", "struct_range_double__struct.html", null ],
    [ "RangeFloat_struct", "struct_range_float__struct.html", null ],
    [ "RangeLabel_struct", "struct_range_label__struct.html", null ],
    [ "RangeSettingDouble_struct", "struct_range_setting_double__struct.html", null ],
    [ "ReadTextOptions_struct", "struct_read_text_options__struct.html", null ],
    [ "ReadTextReport2_struct", "struct_read_text_report2__struct.html", null ],
    [ "ReadTextReport3_struct", "struct_read_text_report3__struct.html", null ],
    [ "ReadTextReport_struct", "struct_read_text_report__struct.html", null ],
    [ "Rect_struct", "struct_rect__struct.html", null ],
    [ "RectangleDescriptor_struct", "struct_rectangle_descriptor__struct.html", null ],
    [ "RectangleFeature_struct", "struct_rectangle_feature__struct.html", null ],
    [ "RectangleMatch_struct", "struct_rectangle_match__struct.html", null ],
    [ "CameraServer::Request", "struct_camera_server_1_1_request.html", null ],
    [ "RGBU64Value_struct", "struct_r_g_b_u64_value__struct.html", null ],
    [ "RGBValue_struct", "struct_r_g_b_value__struct.html", null ],
    [ "RobotBase", "class_robot_base.html", [
      [ "IterativeRobot", "class_iterative_robot.html", null ],
      [ "SampleRobot", "class_sample_robot.html", null ]
    ] ],
    [ "RobotDeleter", "class_robot_deleter.html", null ],
    [ "RobotState", "class_robot_state.html", null ],
    [ "RobotStateInterface", "class_robot_state_interface.html", [
      [ "DriverStation", "class_driver_station.html", null ]
    ] ],
    [ "ROILabel_struct", "struct_r_o_i_label__struct.html", null ],
    [ "ROIProfile_struct", "struct_r_o_i_profile__struct.html", null ],
    [ "RotatedRect_struct", "struct_rotated_rect__struct.html", null ],
    [ "RotationAngleRange_struct", "struct_rotation_angle_range__struct.html", null ],
    [ "SampleScore_struct", "struct_sample_score__struct.html", null ],
    [ "SearchArcInfo_struct", "struct_search_arc_info__struct.html", null ],
    [ "SearchLineInfo_struct", "struct_search_line_info__struct.html", null ],
    [ "SegmentInfo_struct", "struct_segment_info__struct.html", null ],
    [ "SelectParticleCriteria_struct", "struct_select_particle_criteria__struct.html", null ],
    [ "Sendable", "class_sendable.html", [
      [ "LiveWindowSendable", "class_live_window_sendable.html", [
        [ "ADXL345_I2C", "class_a_d_x_l345___i2_c.html", null ],
        [ "ADXL345_SPI", "class_a_d_x_l345___s_p_i.html", null ],
        [ "ADXL362", "class_a_d_x_l362.html", null ],
        [ "AnalogAccelerometer", "class_analog_accelerometer.html", null ],
        [ "AnalogInput", "class_analog_input.html", null ],
        [ "AnalogOutput", "class_analog_output.html", null ],
        [ "AnalogPotentiometer", "class_analog_potentiometer.html", null ],
        [ "BuiltInAccelerometer", "class_built_in_accelerometer.html", null ],
        [ "CANJaguar", "class_c_a_n_jaguar.html", null ],
        [ "CANTalon", "class_c_a_n_talon.html", null ],
        [ "Compressor", "class_compressor.html", null ],
        [ "Counter", "class_counter.html", null ],
        [ "DigitalInput", "class_digital_input.html", null ],
        [ "DigitalOutput", "class_digital_output.html", null ],
        [ "DoubleSolenoid", "class_double_solenoid.html", null ],
        [ "Encoder", "class_encoder.html", null ],
        [ "GyroBase", "class_gyro_base.html", null ],
        [ "PIDController", "class_p_i_d_controller.html", null ],
        [ "PowerDistributionPanel", "class_power_distribution_panel.html", null ],
        [ "PWM", "class_p_w_m.html", null ],
        [ "Relay", "class_relay.html", null ],
        [ "Solenoid", "class_solenoid.html", null ],
        [ "Ultrasonic", "class_ultrasonic.html", null ]
      ] ],
      [ "NamedSendable", "class_named_sendable.html", [
        [ "Command", "class_command.html", null ],
        [ "Scheduler", "class_scheduler.html", null ],
        [ "Subsystem", "class_subsystem.html", null ]
      ] ],
      [ "SendableChooser", "class_sendable_chooser.html", null ],
      [ "Trigger", "class_trigger.html", [
        [ "Button", "class_button.html", [
          [ "InternalButton", "class_internal_button.html", null ],
          [ "JoystickButton", "class_joystick_button.html", null ],
          [ "NetworkButton", "class_network_button.html", null ]
        ] ]
      ] ]
    ] ],
    [ "SetupMatchPatternData_struct", "struct_setup_match_pattern_data__struct.html", null ],
    [ "ShapeDetectionOptions_struct", "struct_shape_detection_options__struct.html", null ],
    [ "ShapeReport_struct", "struct_shape_report__struct.html", null ],
    [ "SimpleEdgeOptions_struct", "struct_simple_edge_options__struct.html", null ],
    [ "SpokeOptions_struct", "struct_spoke_options__struct.html", null ],
    [ "SpokeReport2_struct", "struct_spoke_report2__struct.html", null ],
    [ "SpokeReport_struct", "struct_spoke_report__struct.html", null ],
    [ "StraightEdge_struct", "struct_straight_edge__struct.html", null ],
    [ "StraightEdgeOptions_struct", "struct_straight_edge_options__struct.html", null ],
    [ "StraightEdgeReport2_struct", "struct_straight_edge_report2__struct.html", null ],
    [ "StructuringElement_struct", "struct_structuring_element__struct.html", null ],
    [ "SupervisedColorSegmentationReport_struct", "struct_supervised_color_segmentation_report__struct.html", null ],
    [ "tCANStreamMessage", "structt_c_a_n_stream_message.html", null ],
    [ "Threshold", "class_threshold.html", null ],
    [ "ThresholdData_struct", "struct_threshold_data__struct.html", null ],
    [ "TIFFFileOptions_struct", "struct_t_i_f_f_file_options__struct.html", null ],
    [ "Timer", "class_timer.html", null ],
    [ "ToolWindowOptions_struct", "struct_tool_window_options__struct.html", null ],
    [ "CANTalon::TrajectoryPoint", "struct_c_a_n_talon_1_1_trajectory_point.html", null ],
    [ "TransformBehaviors_struct", "struct_transform_behaviors__struct.html", null ],
    [ "TransformReport_struct", "struct_transform_report__struct.html", null ],
    [ "UserPointSymbol_struct", "struct_user_point_symbol__struct.html", null ],
    [ "View3DOptions_struct", "struct_view3_d_options__struct.html", null ],
    [ "WaveletBandsReport_struct", "struct_wavelet_bands_report__struct.html", null ],
    [ "WaveletOptions_struct", "struct_wavelet_options__struct.html", null ],
    [ "WindowSize_struct", "struct_window_size__struct.html", null ]
];